apiVersion: v1
kind: Service
metadata:
  name: subway-explorer-webapp-service
  labels:
    app: subway-explorer-webapp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: subway-explorer-webapp-pod
  type: LoadBalancer
