apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subway-explorer-webapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subway-explorer-webapp-pod
    spec:
      containers:
        - name: subway-explorer-webapp-container
          image: residentmario/subway-explorer-webapp
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: GMAPS_PROXY_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: webapp-config-map  
                  key: GMAPS_PROXY_SERVICE_URI
            - name: SUBWAY_EXPLORER_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: webapp-config-map
                  key: SUBWAY_EXPLORER_SERVICE_URI
          command: ["/bin/sh"]
          args: ["./scripts/build.sh"]
