apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subway-explorer-api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subway-explorer-api-pod
    spec:
      containers:
        - name: subway-explorer-api-container
          image: residentmario/subway-explorer-api
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: subway-explorer-datastore
              mountPath: /mnt/subway-explorer-datastore/
          env:
            - name: DATABASE_FILEPATH
              valueFrom:
                configMapKeyRef:
                  name: database-config-map
                  key: DATABASE_FILEPATH

      volumes:
        - name: subway-explorer-datastore
          gcePersistentDisk:
            pdName: subway-explorer-datastore
            fsType: ext4
      nodeSelector:
        datastore_node: "true"
