kind: Service
apiVersion: v1
metadata:
  name: subway-explorer-gmaps-proxy-service
spec:
  selector:
    app: subway-explorer-gmaps-proxy-pod
    tier: backend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: http
