kind: Service
apiVersion: v1
metadata:
  name: subway-explorer-gmaps-proxy-service
spec:
  selector:
    app: subway-explorer-gmaps-proxy-pod
  ports:
  - protocol: TCP
    port: 9000
  type: ClusterIP
